# Put your fields here

## Used by "base_timezone.rb"
timezone: "America/Los_Angeles"

## Used by "base_shmem.rb"
shmem:
  shmall: 134217728
  shmmax: 134217728

## Used by "base_php5.rb"
php5:
  memory_limit: "64M"
  upload_max_filesize: "8M"

## Used by "base_passenger.rb"
### passenger:
###   pool_size: 8
###   max_instances: 6

# Secret fields here
<% secrets_yml = File.join(File.dirname(__FILE__), "secrets.yml"); if File.exist?(secrets_yml) %>
<%= File.read(secrets_yml) %>
<% else; puts "WARNING: Couldn't find secrets, please add them to: #{secrets_yml}"; end %>

#-----------------------------------------------------------------------
#
# == FIELDS
#
# This is an AutomateIt fields file. Fields are useful for extracting
# configuration-specific arguments out of your recipe logic, and making
# them easier to share between recipes and access from other programs.
#
# For example, declare fields using YAML:
#
#   foo: bar
#   mydaemon:
#     mykey: myvalue
#
# And retrieve field values from a recipe:
#
#   lookup("foo") # => "bar"
#   lookup("mydaemon") # => {"mykey" => "myvalue"}
#   lookup("mydaemon#mykey") # => "myvalue"
#
# You may use ERB statements within this file. Because this file is
# loaded after the tags, you can use ERB to dynamically set fields for
# specific groups of hosts, e.g.:
#
#   magical: <%#= tagged?("magical_hosts") ? true : false %>
#
# See AutomateIt::FieldManager for further details.
#
#-----------------------------------------------------------------------
